export const recipies = [
  {
    title: "Pasta with Tomato Sauce",
    image:
      "https://www.endofthefork.com/wp-content/uploads/2021/06/1200x1200-pasta-and-sauce.jpg",
    time: 30,
    rating: 4.5,
    ingredients: [
      "1 pound pasta",
      "1 can of crushed tomatoes",
      "2 cloves garlic",
      "1/4 cup olive oil",
      "1/4 teaspoon red pepper flakes",
      "Salt and pepper to taste",
      "Fresh basil for garnish",
    ],
    instructions: [
      "Cook the pasta according to package directions.",
      "In a large skillet, heat the olive oil over medium heat. Add the garlic and red pepper flakes and cook for 1 minute.",
      "Add the crushed tomatoes to the skillet and simmer for 10 minutes.",
      "Add the cooked pasta to the skillet and toss to coat with the sauce.",
      "Season with salt and pepper to taste.",
      "Garnish with fresh basil and serve.",
    ],
  },
  {
    title: "Grilled Salmon with Avocado Salsa",
    image:
      "https://i.ytimg.com/vi/oY3S6acQ9lE/maxresdefault.jpg",
    time: 25,
    rating: 4.8,
    ingredients: [
      "4 salmon fillets",
      "2 ripe avocados",
      "1/2 red onion",
      "1/4 cup chopped fresh cilantro",
      "Juice of 1 lime",
      "Salt and pepper to taste",
      "Olive oil for grilling",
    ],
    instructions: [
      "Preheat grill to medium-high heat.",
      "Brush salmon fillets with olive oil and season with salt and pepper to taste.",
      "Grill salmon for 4-5 minutes per side or until cooked through.",
      "In a medium bowl, combine diced avocado, diced red onion, chopped cilantro, lime juice, salt, and pepper.",
      "Serve grilled salmon topped with avocado salsa.",
    ],
  },
  {
    title: "Shrimp Scampi Linguine",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6NK-D4XEA5qti6dyMX0bPA325U7WZ1iAj3A&usqp=CAU",
    time: 25,
    rating: 4.6,
    ingredients: [
      "1 pound linguine",
      "1 pound large shrimp, peeled and deveined",
      "1/2 cup unsalted butter",
      "1/2 cup olive oil",
      "6 cloves garlic, minced",
      "1/2 teaspoon red pepper flakes",
      "1/2 cup dry white wine",
      "1/2 cup chicken broth",
      "1/2 cup grated Parmesan cheese",
      "1/4 cup chopped fresh parsley",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Cook linguine according to package instructions.",
      "In a large skillet, heat butter and olive oil over medium heat. Add garlic and red pepper flakes and cook until fragrant.",
      "Add shrimp to the skillet and cook until pink.",
      "Add white wine and chicken broth to the skillet and bring to a simmer.",
      "Add cooked linguine to the skillet and toss to coat with sauce.",
      "Season with salt and pepper to taste.",
      "Garnish with Parmesan cheese and parsley before serving.",
    ],
  },
  {
    title: "Roasted Chicken with Vegetables",
    image:
      "https://thecozyapron.com/wp-content/uploads/2015/11/roasted-chicken_thecozyapron_11-15-15_1.jpg",
    time: 60,
    rating: 4.7,
    ingredients: [
      "1 whole chicken",
      "3 carrots, chopped",
      "2 celery stalks, chopped",
      "1 onion, chopped",
      "3 garlic cloves, minced",
      "3 tbsp olive oil",
      "1 tbsp dried thyme",
      "1 tbsp dried rosemary",
      "1 tbsp dried sage",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "In a large bowl, mix together the chopped carrots, celery, onion, and garlic.",
      "Add 2 tablespoons of olive oil, thyme, rosemary, sage, salt, and pepper. Mix well.",
      "Pat the chicken dry with paper towels, and season the inside and outside of the chicken with salt and pepper.",
      "Place the chicken in a roasting pan, and stuff the chicken cavity with the vegetable mixture.",
      "Tie the legs together with kitchen twine, and tuck the wings under the body of the chicken.",
      "Brush the remaining tablespoon of olive oil over the chicken skin.",
      "Roast the chicken in the preheated oven for 60-75 minutes, or until the internal temperature of the chicken reaches 165°F (75°C).",
      "Let the chicken rest for 10 minutes before carving and serving with the roasted vegetables.",
    ],
  },
];
